import type { Metadata } from "next";
import { Geist, Geist_Mono, Lemon, Caveat } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme/theme-provider";
import { Toaster } from "@/components/ui/sonner";
import { cn } from "@/lib/utils";
import { fontAerosoldis } from "@/public/fonts";
import { MusicPlayerProvider } from "@/components/dashboard/home/MusicPlayerContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const lemon = Lemon({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-lemon",
});

const caveat = Caveat({
  subsets: ["latin"],
  weight: "600",
  variable: "--font-caveat",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          `${geistSans.variable} ${geistMono.variable} ${lemon.variable} ${caveat.variable} antialiased`,
          fontAerosoldis.variable
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <MusicPlayerProvider>{children}</MusicPlayerProvider>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
